Leave-Management/Models/ViewModels/LeaveAllocationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Leave_Management.Data;

namespace Leave_Management.Models.ViewModels
{
    public class LeaveAllocationViewModel
    {
        public int Id { get; set; }

        [Display(Name = "تعداد روز")]
        [Required(ErrorMessage = "تعداد روز باید وارد شود.")]
        public int NumberOfDays { get; set; }

        public int Period { get; set; }

        [Display(Name = "تاریخ ایجاد")]
        [DataType(DataType.DateTime)]
        public DateTime DateCreated { get; set; }

        [Display(Name = "نام کارمند")]
        public string EmployeeId { get; set; }

        public LeaveTypeDetailsViewModel LeaveType { get; set; }

        [Display(Name = "دلیل مرخصی")]
        public int LeaveTypeId { get; set; }
    }

    public class LeaveAllocationCreateViewModel
    {
        public int NumberUpdated { get; set; }
        public List<LeaveTypeDetailsViewModel> LeaveTypes { get; set; }
    }

    public class LeaveAllocationsViewViewModel
    {
        public EmployeeViewModel Employee { get; set; }
        public string EmployeeId { get; set; }
        public List<LeaveAllocationViewModel> LeaveAllocations { get; set; }
    }

    public class LeaveAllocationEditViewModel
    {
        public int Id { get; set; }

        [Display(Name = "تعداد روز")]
        [Required(ErrorMessage = "تعداد روز باید وارد شود.")]
        public int NumberOfDays { get; set; }

        public LeaveTypeDetailsViewModel LeaveType { get; set; }

        public EmployeeViewModel Employee { get; set; }
        public string EmployeeId { get; set; }
    }
}

Leave-Management/Controllers/LeaveAllocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Leave_Management.Contracts;
using Leave_Management.Data;
using Leave_Management.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Leave_Management.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class LeaveAllocationController : Controller
    {
        #region Variables DI

        private readonly ILeaveTypeRepository _leaveTypeRepository;
        private readonly ILeaveAllocationRepository _leaveAllocationRepository;
        private readonly IMapper _mapper;
        private readonly UserManager<Employee> _userManager;

        #endregion

        #region Constructor

        public LeaveAllocationController(ILeaveTypeRepository leaveTypeRepository,
            ILeaveAllocationRepository leaveAllocationRepository,
            IMapper mapper, UserManager<Employee> userManager)
        {
            _leaveTypeRepository = leaveTypeRepository;
            _leaveAllocationRepository = leaveAllocationRepository;
            _mapper = mapper;
            _userManager = userManager;
        }

        #endregion

        #region Index

        // GET: LeaveAllocation
        public ActionResult Index()
        {
            var leaveTypes = _leaveTypeRepository.FindAll().ToList();
            var mappedLeaveTypes =
                _mapper.Map<List<LeaveType>, List<LeaveTypeDetailsViewModel>>(leaveTypes);
            var model = new LeaveAllocationCreateViewModel
            {
                LeaveTypes = mappedLeaveTypes,
                NumberUpdated = 0
            };
            return View(model);
        }

        #endregion

        #region SetLeave

        public IActionResult SetLeave(int id)
        {
            var leaveType = _leaveTypeRepository.FindById(id);
            var employees = _userManager.GetUsersInRoleAsync("Employee").Result;
            foreach (var employee in employees)
            {
                if (_leaveAllocationRepository.CheckAllocation(id, employee.Id))
                    continue;
                var allocation = new LeaveAllocationViewModel
                {
                    DateCreated = DateTime.Now,
                    EmployeeId = employee.Id,
                    LeaveTypeId = id,
                    NumberOfDays = leaveType.DefaultDays,
                    Period = DateTime.Now.Year
                };
                var leaveAllocation = _mapper.Map<LeaveAllocation>(allocation);
                _leaveAllocationRepository.Create(leaveAllocation);
            }

            return RedirectToAction(nameof(Index));
        }

        #endregion

        #region List Employees

        public IActionResult ListEmployees()
        {
            var employees = _userManager.GetUsersInRoleAsync("Employee").Result;
            var model = _mapper.Map<List<EmployeeViewModel>>(employees);
            return View(model);
        }

        #endregion

        #region Details

        // GET: LeaveAllocation/Details/5
        public ActionResult Details(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();
            var employee = _mapper.Map<EmployeeViewModel>(_userManager.FindByIdAsync(id).Result);
            var period = DateTime.Now.Year;

            var allocations =
                _mapper.Map<List<LeaveAllocationViewModel>>(_leaveAllocationRepository.GetLeaveAllocationsByEmployee(id));

            var model = new LeaveAllocationsViewViewModel
            {
                Employee = employee,
                LeaveAllocations = allocations,
                EmployeeId = id
            };
            return View(model);
        }

        #endregion

        #region Edit

        // GET: LeaveAllocation/Edit/5
        public ActionResult Edit(int id)
        {
            var leaveAllocation = _leaveAllocationRepository.FindById(id);
            if (leaveAllocation == null)
                return BadRequest();
            var model = _mapper.Map<LeaveAllocationEditViewModel>(leaveAllocation);

            return View(model);
        }

        // POST: LeaveAllocation/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LeaveAllocationEditViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(viewModel);
                }

                var record = _leaveAllocationRepository.FindById(viewModel.Id);
                record.NumberOfDays = viewModel.NumberOfDays;
                var isSuccess = _leaveAllocationRepository.Update(record);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "بروز خطا در ثبت اطلاعات");
                    return View(viewModel);
                }

                return RedirectToAction(nameof(Details), new { id = viewModel.EmployeeId });
            }
            catch
            {
                ModelState.AddModelError("", "بروز خطا در ثبت اطلاعات");
                return View(viewModel);
            }
        }

        #endregion

        #region Delete

        // GET: LeaveAllocation/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LeaveAllocation/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        #endregion

        #region Create

        // GET: LeaveAllocation/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeaveAllocation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        #endregion
    }
}

Leave-Management/Views/LeaveAllocation/Details.cshtml
@model Leave_Management.Models.ViewModels.LeaveAllocationsViewViewModel

@{
    ViewData["Title"] = "Details";
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = "~/Views/Shared/_AdminLTE.cshtml";
}

<h3>جزئیات مرخصی - @Model.Employee.Firstname @Model.Employee.Lastname</h3>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Firstname)
        </dt>

        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Firstname)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Lastname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Lastname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.PhoneNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.PhoneNumber)
        </dd>
        @*<dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.TaxId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.TaxId)
        </dd>*@
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.DateJoined)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.DateJoined)
        </dd>
        @*<dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Employee.DateCreated)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Employee.DateCreated)
        </dd>*@
    </dl>
</div>

<hr />
<br/>
<h4>مرخصی های اختصاص یافته</h4>
@{
    <div class="card">
        <ul class="list-group list-group-flush">
            @foreach (var item in Model.LeaveAllocations)
            {
            <li class="list-group-item">
                <h6>
                    @item.LeaveType.Name 
                    <span class="badge badge-info">
                        @item.NumberOfDays
                    </span>
                    <a asp-action="Edit" asp-controller="LeaveAllocation" asp-route-id="@item.Id" class="btn btn-outline-warning btn-sm text-black-50">
                        <i class="fa fa-pencil"></i> ویرایش
                    </a>
                </h6>
            </li>
            }
        </ul>
    </div>
}
<br/>
<div>
    <a asp-action="ListEmployees" class="btn btn-outline-secondary">بازگشت</a>
</div>

Leave-Management/Views/LeaveAllocation/Edit.cshtml
@model Leave_Management.Models.ViewModels.LeaveAllocationEditViewModel

@{
    ViewData["Title"] = "ویرایش " + @Model.LeaveType.Name + " اختصاص داده شده به " + @Model.Employee.Firstname + " " + @Model.Employee.Lastname;
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="EmployeeId" />

            <div class="form-group">
                <label asp-for="NumberOfDays" class="control-label"></label>
                <input asp-for="NumberOfDays" class="form-control" />
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="ثبت" class="btn btn-primary" />
                <a class="btn btn-outline-secondary" asp-action="Index">بازگشت</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Leave-Management/Views/LeaveAllocation/Index.cshtml
@model Leave_Management.Models.ViewModels.LeaveAllocationCreateViewModel

@{
    ViewData["Title"] = "اختصاص مرخصی های سیستمی به کارمندان";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <!--card-header-->
            <div class="card-header">
                <h3 class="card-title">انواع مرخصی های سیستمی</h3>
            </div>
            <!-- /.card-header -->
            <!--card body-->
            <div class="card-body">
                <div id="example2_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12 col-md-6"></div>
                        <div class="col-sm-12 col-md-6"></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="tblData" class="table table-bordered table-hover dataTable" role="grid">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="نوع مرخصی : activate to sort column descending" style="width: 250px;">
                                            نوع مرخصی
                                        </th>

                                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="عملیات: activate to sort column ascending" style="width: 416px;">عملیات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.LeaveTypes)
                                    {
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">@Html.DisplayFor(modelItem => item.Name)</td>
                                            <td>
                                                <a class="btn btn-outline-success btn-sm" asp-controller="LeaveAllocation" asp-action="SetLeave" asp-route-id="@item.Id">
                                                    <i class="fa fa-pencil"></i>
                                                    اختصاص به کارمندان
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 col-md-5"></div>
                        <div class="col-sm-12 col-md-7">
                            @*<div class="dataTables_paginate paging_simple_numbers" id="example2_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0" class="page-link">قبلی</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0" class="page-link">6</a></li><li class="paginate_button page-item next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0" class="page-link">بعدی</a></li></ul></div>*@
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>


@section Scripts{
    <script>
        $(document).ready(function () {
            $('#tblData').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Persian.json"
                }
            });
        });
    </script>
}

Leave-Management/Views/LeaveAllocation/ListEmployees.cshtml
@model IEnumerable<Leave_Management.Models.ViewModels.EmployeeViewModel>

@{
    ViewData["Title"] = "فهرست کارمندان";
}
<br />
<br />

<div class="row">
    <div class="col-12">
        <div class="card">
            <!--card-header-->
            <div class="card-header">
                <h3 class="card-title">انواع مرخصی های سیستمی</h3>
            </div>
            <!-- /.card-header -->
            <!--card body-->
            <div class="card-body">
                <div id="example2_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12 col-md-6"></div>
                        <div class="col-sm-12 col-md-6"></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="tblData" class="table table-bordered table-hover dataTable" role="grid">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="@Html.DisplayNameFor(model => model.Firstname) : activate to sort column descending" style="width: 250px;">
                                            @Html.DisplayNameFor(model => model.Firstname)
                                        </th>
                                        <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="@Html.DisplayNameFor(model => model.Lastname) : activate to sort column descending" style="width: 250px;">
                                            @Html.DisplayNameFor(model => model.Lastname)
                                        </th>
                                        <th class="sorting_asc" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-sort="ascending" aria-label="@Html.DisplayNameFor(model => model.Email) : activate to sort column descending" style="width: 250px;">
                                            @Html.DisplayNameFor(model => model.Email)
                                        </th>

                                        <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" aria-label="جزئیات: activate to sort column ascending" style="width: 416px;">عملیات</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr role="row" class="odd">
                                            <td class="sorting_1">@Html.DisplayNameFor(model => model.Firstname)</td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Lastname)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Email)
                                            </td>
                                            <td>
                                                @*<a asp-action="Details" asp-route-id="@item.Id">Details</a> |*@

                                                <a class="btn btn-outline-success btn-sm" asp-controller="LeaveAllocation" asp-action="Details" asp-route-id="@item.Id">
                                                    <i class="fa fa-search" aria-hidden="true"></i>
                                                    جزئیات
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 col-md-5"></div>
                        <div class="col-sm-12 col-md-7">
                            @*<div class="dataTables_paginate paging_simple_numbers" id="example2_paginate"><ul class="pagination"><li class="paginate_button page-item previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0" class="page-link">قبلی</a></li><li class="paginate_button page-item active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0" class="page-link">1</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0" class="page-link">2</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0" class="page-link">3</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0" class="page-link">4</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0" class="page-link">5</a></li><li class="paginate_button page-item "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0" class="page-link">6</a></li><li class="paginate_button page-item next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0" class="page-link">بعدی</a></li></ul></div>*@
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            $('#tblData').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.21/i18n/Persian.json"
                }
            });
        });
    </script>
}