Leave-Management/Controllers/LeaveRequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Leave_Management.Contracts;
using Leave_Management.Data;
using Leave_Management.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Leave_Management.Controllers
{
    [Authorize]
    public class LeaveRequestController : Controller
    {
        #region Variables

        private readonly ILeaveAllocationRepository _leaveAllocationRepo;
        private readonly ILeaveRequestRepository _leaveRequestRepo;
        private readonly ILeaveTypeRepository _leaveTypeRepo;
        private readonly IMapper _mapper;
        private readonly UserManager<Employee> _userManager;

        #endregion

        #region Construsctor

        public LeaveRequestController(ILeaveRequestRepository leaveRequestRepo,
            IMapper mapper,
            UserManager<Employee> userManager, ILeaveTypeRepository leaveTypeRepo, ILeaveAllocationRepository leaveAllocationRepo)
        {
            _leaveRequestRepo = leaveRequestRepo;
            _mapper = mapper;
            _userManager = userManager;
            _leaveTypeRepo = leaveTypeRepo;
            _leaveAllocationRepo = leaveAllocationRepo;
        }

        #endregion

        #region Index

        [Authorize(Roles = "Administrator")]
        // GET: LeaveRequest
        public ActionResult Index()
        {
            var leaveRequests = _leaveRequestRepo.FindAll();
            var leaveRequestsModel = _mapper.Map<List<LeaveRequestViewModel>>(leaveRequests);
            var model = new LeaveRequestAdminViewModel
            {
                TotalRequests = leaveRequestsModel.Count,
                ApprovedRequests = leaveRequestsModel.Count(x => x.Approved == true),
                RejectedRequests = leaveRequestsModel.Count(x => x.Approved == false),
                PendingRequests = leaveRequestsModel.Count(x => x.Approved == null),
                LeaveRequest = leaveRequestsModel
            };
            return View(model);
        }

        #endregion

        #region Create

        // GET: LeaveRequest/Create
        public ActionResult Create()
        {
            var leaveTypes = _leaveTypeRepo.FindAll();
            var leaveTypeItems = leaveTypes.Select(x => new SelectListItem
            {
                Text = x.Name,
                Value = x.Id.ToString()
            });
            var model = new LeaveRequestCreateViewModel
            {
                LeaveTypes = leaveTypeItems
            };
            return View(model);
        }

        // POST: LeaveRequest/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LeaveRequestCreateViewModel viewModel)
        {
            try
            {
                var leaveTypes = _leaveTypeRepo.FindAll();
                var leaveTypeItems = leaveTypes.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
                viewModel.LeaveTypes = leaveTypeItems;

                DateTime startDate = Convert.ToDateTime(viewModel.StartDate);
                DateTime endDate = Convert.ToDateTime(viewModel.EndDate);

                if (!ModelState.IsValid)
                    return View(viewModel);

                if (DateTime.Compare(startDate, endDate) > 1)
                {
                    ModelState.AddModelError("", "تاریخ پایان مرخصی نبایست کمتر از تاریخ شروع آن باشد.");
                    return View(viewModel);
                }

                var employee = _userManager.GetUserAsync(User).Result;
                if (employee == null)
                    return BadRequest();
                var allocation =
                    _leaveAllocationRepo.GetLeaveAllocationsByEmployeeAndType(employee.Id, viewModel.LeaveTypeId.Value);

                if (allocation == null)
                {
                    ModelState.AddModelError("", "برای کاربر شما در سیستم مرخصی مورد نظر تعیین نگردیده است.");
                    return View(viewModel);
                }
                int daysRequested = (int)(startDate.Date - endDate.Date).TotalDays;
                if (daysRequested > allocation.NumberOfDays)
                {
                    ModelState.AddModelError("", "تعداد روزهای درخواستی بیشتر از حد مجاز روزهای مرخصی شما است.");
                    return View(viewModel);
                }

                var leaveRequestModel = new LeaveRequestViewModel
                {
                    RequestingEmployeeId = employee.Id,
                    DateRequested = DateTime.Now,
                    StartDate = startDate,
                    EndDate = endDate,
                    Approved = null,
                    LeaveTypeId = (int)viewModel.LeaveTypeId,
                    DateActioned = DateTime.MinValue,
                    Cancelled = false,
                    RequestComments = viewModel.RequestComments
                };

                var leaveRequest = _mapper.Map<LeaveRequest>(leaveRequestModel);
                var isSuccess = _leaveRequestRepo.Create(leaveRequest);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "بروز خطا در ثبت اطلاعات");
                    return View(viewModel);
                }

                return RedirectToAction(nameof(MyLeave));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "بروز خطا در ثبت اطلاعات" + "\n" + ex.Message);
                return View(viewModel);
            }
        }

        #endregion

        #region Details

        // GET: LeaveRequest/Details/5
        public ActionResult Details(int id)
        {
            var leaveRequest = _leaveRequestRepo.FindById(id);
            if (leaveRequest == null)
                return NotFound();
            var model = _mapper.Map<LeaveRequestViewModel>(leaveRequest);
            return View(model);
        }

        #endregion

        #region Approve Leave Request

        public IActionResult ApproveRequest(int id)
        {
            try
            {
                var leaveRequest = _leaveRequestRepo.FindById(id);
                if (leaveRequest == null)
                    return NotFound();
                var employeeId = leaveRequest.RequestingEmployeeId;
                var leaveTypeId = leaveRequest.LeaveTypeId;

                var allocation = _leaveAllocationRepo.GetLeaveAllocationsByEmployeeAndType(employeeId, leaveTypeId);
                int daysRequested = (int)(leaveRequest.EndDate.Date - leaveRequest.StartDate.Date).TotalDays;

                allocation.NumberOfDays -= daysRequested;
                if (allocation.NumberOfDays >= 0)
                {
                    leaveRequest.Approved = true;
                    leaveRequest.DateActioned = DateTime.Now;
                    var user = _userManager.GetUserAsync(User).Result;
                    leaveRequest.ApprovedById = user.Id;

                    var isSuccessleaveRequest = _leaveRequestRepo.Update(leaveRequest);
                    var isSuccessLeaveAllocation = _leaveAllocationRepo.Update(allocation);

                    if (!isSuccessleaveRequest || !isSuccessLeaveAllocation)
                    {
                        return RedirectToAction("Details", routeValues: id);
                    }

                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction("Details", routeValues: id);

            }
            catch
            {
                return RedirectToAction("Details", routeValues: id);
            }
        }

        #endregion

        #region Reject Leave Request

        public IActionResult RejectRequest(int id)
        {
            try
            {
                var leaveRequest = _leaveRequestRepo.FindById(id);
                if (leaveRequest == null)
                    return NotFound();
                leaveRequest.Approved = false;
                leaveRequest.DateActioned = DateTime.Now;
                var user = _userManager.GetUserAsync(User).Result;
                leaveRequest.ApprovedById = user.Id;

                var isSuccess = _leaveRequestRepo.Update(leaveRequest);
                if (!isSuccess)
                {
                    return RedirectToAction("Details", routeValues: id);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction("Details", routeValues: id);
            }


        }

        #endregion

        #region MyLeave

        public ActionResult MyLeave()
        {
            var employee = _userManager.GetUserAsync(User).Result;
            var employeeId = employee.Id;
            var employeeAllocations = _leaveAllocationRepo.GetLeaveAllocationsByEmployee(employeeId);
            var employeeRequests = _leaveRequestRepo.GetLeaveRequestByEmployee(employeeId);

            var employeeAllocationModel = _mapper.Map<List<LeaveAllocationViewModel>>(employeeAllocations);
            var employeeRequestModel = _mapper.Map<List<LeaveRequestViewModel>>(employeeRequests);

            var model = new LeaveRequestEmployeeViewViewModel
            {
                LeaveAllocations = employeeAllocationModel,
                LeaveRequests = employeeRequestModel
            };
            return View(model);
        }

        #endregion

        #region CancelRequest

        public IActionResult CancelRequest(int id)
        {
            var leaveRequest = _leaveRequestRepo.FindById(id);
            if (leaveRequest == null)
                return RedirectToAction(nameof(Index));
            leaveRequest.Cancelled = true;
            _leaveRequestRepo.Update(leaveRequest);

Leave-Management/Controllers/LeaveTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using Leave_Management.Contracts;
using Leave_Management.Data;
using Leave_Management.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Leave_Management.Controllers
{
    [Authorize(Roles = "Administrator,Employee")]
    public class LeaveTypesController : Controller
    {
        private readonly ILeaveTypeRepository _repo;
        private readonly IMapper _mapper;

        public LeaveTypesController(ILeaveTypeRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }

        // GET: LeaveTypes
        public ActionResult Index()
        {
            var leaveTypes = _repo.FindAll().ToList();
            var model = _mapper.Map<List<LeaveType>, List<LeaveTypeDetailsViewModel>>(leaveTypes);
            return View(model);
        }

        // GET: LeaveTypes/Details/5
        public ActionResult Details(int id)
        {
            if (!_repo.IsExists(id))
                return NotFound();
            var leaveType = _repo.FindById(id);
            var model = _mapper.Map<LeaveTypeDetailsViewModel>(leaveType);
            return View(model);
        }

        // GET: LeaveTypes/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(LeaveTypeCreateViewModel viewModel)
        {
            try
            {
                // TODO: Add insert logic here
                if (!ModelState.IsValid) return RedirectToAction(nameof(Index));

                var leaveType = _mapper.Map<LeaveType>(viewModel);
                leaveType.DateCreated = DateTime.Now;

                if (_repo.Create(leaveType))
                    return RedirectToAction(nameof(Index));

                ModelState.AddModelError("", "بروز خطا در ثبت اطلاعات در سیستم");
                return View(viewModel);

            }
            catch
            {
                ModelState.AddModelError("", "بروز خطا در ثبت اطلاعات در سیستم");
                return View(viewModel);
            }
        }

        
        // GET: LeaveTypes/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            var isExists = _repo.IsExists(id);
            if (isExists == false)
                return NotFound();
            var leaveType = _repo.FindById(id);
            var model = _mapper.Map<LeaveTypeDetailsViewModel>(leaveType);

            return View(model);
        }

        
        // POST: LeaveTypes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(LeaveTypeDetailsViewModel viewModel)
        {
            try
            {
                // TODO: Add update logic here
                if (!ModelState.IsValid)
                    return View(viewModel);

                var leaveType = _mapper.Map<LeaveType>(viewModel);
                leaveType.DateCreated = viewModel.DateCreated;
                if (_repo.Update(leaveType))
                    return RedirectToAction(nameof(Index));

                ModelState.AddModelError("", "بروز خطا در به روز رسانی اطلاعات");
                return View(viewModel);
            }
            catch
            {
                ModelState.AddModelError("", "بروز خطا در به روز رسانی اطلاعات");
                return View(viewModel);
            }
        }

        // GET: LeaveTypes/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            var isExists = _repo.IsExists(id);
            if (isExists == false)
                return NotFound();

            var leaveType = _repo.FindById(id);
            //var model = _mapper.Map<LeaveTypeDetailsViewModel>(leaveType);

            //return View(model);

            if (!_repo.Delete(leaveType))
                return BadRequest();
            return RedirectToAction(nameof(Index));
        }

        // POST: LeaveTypes/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id, LeaveTypeDetailsViewModel viewModel)
        {
            try
            {
                // TODO: Add delete logic here
                if (_repo.IsExists(id) == false)
                    return NotFound();

                var leaveYpe = _repo.FindById(id);
                if (_repo.Delete(leaveYpe))
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", "بروز خطا در حذف اطلاعات از سیستم");
                return View(viewModel);
            }
            catch
            {
                ModelState.AddModelError("", "بروز خطا در حذف اطلاعات از سیستم");
                return View(viewModel);
            }
        }
    }
}

Leave-Management/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Leave_Management.Data
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - اتوماسیون مدیریت مرخصی </title>



    <!-- :: CSS -->
    <!-- :: Bootstrap -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

    <!-- :: Bootstrap RTL -->
    <link href="~/lib/bootstrap-rtl/bootstrap-rtl.css" rel="stylesheet" />

    <!-- :: DataTables -->
    <link href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet" />

    <!-- :: DataTables BootStrap CSS -->
    <link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet" />

    <!-- :: Font Awesome 4.7 -->
    @*<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">*@
    <link href="~/lib/font-awsome/css/all.css" rel="stylesheet" />

    <!-- :: JQuery UI -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- :: Site CSS -->
    <link rel="stylesheet" href="~/css/site.css" />



    <!-- :: JS -->
    <!-- :: jQuery -->
    <script src="~/lib/jquery/dist/jquery.js"></script>

    <!-- :: Popper -->
    <script src="~/lib/popper/popper.js"></script>

    <!-- :: Bootstrap -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    <!-- :: DataTables -->
    <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

    <!-- :: Font Awesome Latest Edition -->
    @*<script src="https://kit.fontawesome.com/22fb028b55.js" crossorigin="anonymous"></script>*@
    <script src="~/lib/font-awsome/js/all.js" type="text/javascript"></script>



</head>
<body style="text-align: right; direction: rtl">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">نرم افزار اتوماسیون مرخصی ها</a>
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial"/>
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                                  <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">صفحه اصلی</a>
                            </li>*@

                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        مدیریت مرخصی ها
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="LeaveTypes" asp-action="Index" style="font-size: small">مدیریت مرخصی ها</a>
                                        <a class="dropdown-item" asp-controller="LeaveAllocation" asp-action="Index" style="font-size: small">اختصاص مرخصی به کارمندان</a>
                                        <a class="dropdown-item" asp-controller="LeaveAllocation" asp-action="ListEmployees" style="font-size: small">فهرست کارمندان</a>
                                        <a class="dropdown-item" asp-controller="LeaveRequest" asp-action="Index" style="font-size: small">گزارش درخواست های مرخصی</a>
                                        <a class="dropdown-item" asp-controller="LeaveRequest" asp-action="Create" style="font-size: small">ثبت درخواست مرخصی</a>
                                    </div>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        مرخصی ها
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="" asp-controller="LeaveRequest" asp-action="MyLeave" style="font-size: small">مرخصی های من</a>
                                        <a class="dropdown-item" asp-area="" asp-controller="LeaveRequest" asp-action="Create" style="font-size: small">درخواست مرخصی جدید</a>
                                        @*<a class="dropdown-item" href="#">Another action</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="#">Something else here</a>*@
                                    </div>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br />
    <br />
    <br />

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - نرم افزار اتوماسیون مرخصی ها  - <a asp-area="" asp-controller="Home" asp-action="Privacy">سیاسیت محرمانگی</a>
        </div>
    </footer>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>